name: Manual Release PR
# NOTE: automatic commits/ pr of github bots will NOT dispatch any other actions afterwards

# NOTE: github bot can't push files to main if the branch is protected, so we split the release phase to:
# 1. a manual step that changes files and does a PR of a new branch.
# 2. after PR is approved manually the actual release step is done
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build-release-pr:
    name: Build Release PR
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push changes.
      pull-requests: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history so that git log works correctly

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tomlkit build twine

      - name: Update files for release
        id: update_files
        run: |
          new_version=$(python .github/workflows/manual_release_pr_update_files.py ${{ github.event.inputs.release_type }})
          echo "new_version=${new_version}" >> $GITHUB_OUTPUT

      # ===== test the package
      - name: Build package
        run: python -m build

      - name: Install built package
        run: |
          pip install pytest dist/*.whl

      - name: Create tests directory and copy files
        run: |
          mkdir -p /tests
          cp -r ./tests/* /tests
          pytest --no-cov -c /dev/null --rootdir /tests

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: version-update-${{ github.event.inputs.release_type }}
          title: "Bump version to ${{ steps.update_files.outputs.new_version }}"
          body: "Bump version to ${{ steps.update_files.outputs.new_version }}"
          commit-message: "Bump version to ${{ steps.update_files.outputs.new_version }}"
