name: Manual Release PR

# NOTE: github bot can't push files to main if the branch is protected, so we split the release phase to:
# 1. a manual step that changes files and does a PR of a new branch.
# 2. after PR is approved manually the actual release step is done
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  update-version:
    name: Update Version in Branch
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push changes.
      pull-requests: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tomlkit

      - name: Update pyproject.toml
        id: update_pyproject
        run: |
          new_version=$(python release_utils/update_pyproject.py ${{ github.event.inputs.release_type }})
          echo "new_version=${new_version}" >> $GITHUB_OUTPUT

      # ===== test the package
      - name: Build package
        run: python -m build

      - name: Install built package
        run: |
          pip install pytest dist/*.whl

      - name: Run tests
        run: |
          pytest /tests

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: version-update-${{ github.event.inputs.release_type }}
          title: "Bump version to ${{ steps.update_pyproject.outputs.new_version }}"
          body: "Bump version to ${{ steps.update_pyproject.outputs.new_version }}"
          commit-message: "Bump version to ${{ steps.update_pyproject.outputs.new_version }}"
