name: Post Release PR

on:
  pull_request:
    types: [closed]

jobs:
  build-and-publish:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'Bump version to')
 
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      # both below are mandatory for pypi publishing
      name: release
      url: https://pypi.org/p/parametric
    permissions:
      # this permission is mandatory for trusted publishing in pypi
      id-token: write 
      # Give the default GITHUB_TOKEN write permission to commit and push changes.
      # Used by both softprops/action-gh-release@v2 and stefanzweifel/git-auto-commit-action@v5
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 

      - name: Install dependencies
        # build and twine for "build package" step
        run: |
          python -m pip install --upgrade pip
          pip install build twine
 
      - name: Get Version From pyproject.toml
        id: get_new_version
        run: |
          echo "new_version=v$(grep -Po '(?<=version = ")[^"]*' pyproject.toml)" >> $GITHUB_OUTPUT

      - name: Build package
        run: python -m build

      - name: Release and Tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.get_new_version.outputs.new_version }}"

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
